message(STATUS "cmake-deb .cmake")

set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/License.txt")

set(CPACK_PACKAGE_VERSION_MAJOR "${PROJECT_VER_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${PROJECT_VER_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${PROJECT_VER_PATCH}")

set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")

set(CPACK_DEBIAN_PACKAGE_SECTION "main")
set(CPACK_GENERATOR "DEB")

set(NEXUS_DEB_TEMPLATE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/cmake/cmake-deb/templates")

# Template VARS
set(NEXUS_DEB_PACKAGE_NAME ${CPACK_DEBIAN_PACKAGE_NAME})
set(NEXUS_DEB_EXECUTABLE_NAME ${CPACK_DEBIAN_PACKAGE_NAME})
set(NEXUS_DEB_INIT_TYPE "systemd")
set(NEXUS_DEBIAN_DIR "${CMAKE_CURRENT_BINARY_DIR}/debian/DEBIAN")
set(NEXUS_DEBIAN_LOG_DIR "${CMAKE_CURRENT_BINARY_DIR}/log")

set(NEXUS_DEB_INSTALL_DIR "/usr/bin")

set(NEXUS_DEB_DAEMON_ENTRY "${NEXUS_DEB_INSTALL_DIR}/${NEXUS_DEB_EXECUTABLE_NAME}")
set(SYSTEMD_SERVICE_FILE "${CPACK_DEBIAN_PACKAGE_NAME}.service")

# Generate Control Templates (pre-install)
configure_file("${NEXUS_DEB_TEMPLATE_DIR}/preinst" "${NEXUS_DEBIAN_DIR}/preinst"
        FILE_PERMISSIONS
        OWNER_READ OWNER_EXECUTE OWNER_WRITE
        GROUP_READ GROUP_EXECUTE
        WORLD_READ WORLD_EXECUTE
        @ONLY)

# Generate Control Templates (post-install)
configure_file("${NEXUS_DEB_TEMPLATE_DIR}/postinst" "${NEXUS_DEBIAN_DIR}/postinst"
        FILE_PERMISSIONS
        OWNER_READ OWNER_EXECUTE OWNER_WRITE
        GROUP_READ GROUP_EXECUTE
        WORLD_READ WORLD_EXECUTE
        @ONLY)

# Generate Control Templates (pre-rm)
configure_file("${NEXUS_DEB_TEMPLATE_DIR}/prerm" "${NEXUS_DEBIAN_DIR}/prerm"
        FILE_PERMISSIONS
        OWNER_READ OWNER_EXECUTE OWNER_WRITE
        GROUP_READ GROUP_EXECUTE
        WORLD_READ WORLD_EXECUTE
        @ONLY)

# Generate Control Templates (post-rm)
configure_file("${NEXUS_DEB_TEMPLATE_DIR}/postrm" "${NEXUS_DEBIAN_DIR}/postrm"
        FILE_PERMISSIONS
        OWNER_READ OWNER_EXECUTE OWNER_WRITE
        GROUP_READ GROUP_EXECUTE
        WORLD_READ WORLD_EXECUTE
        @ONLY)

# set scripts
set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${NEXUS_DEBIAN_DIR}/preinst;${NEXUS_DEBIAN_DIR}/postinst;${NEXUS_DEBIAN_DIR}/prerm;${NEXUS_DEBIAN_DIR}/postrm;")

install(DIRECTORY DESTINATION "/etc/${CPACK_DEBIAN_PACKAGE_NAME}")

include(CPack)